#!/bin/sh

DAEMON_NAME="aesdsocket"
DAEMON_PATH="/usr/bin/aesdsocket"
PIDFILE="/var/run/aesdsocket.pid"
DAEMON_OPTS="-d"

case "$1" in
    start)
        echo "Starting $DAEMON_NAME"
        start-stop-daemon --start --quiet --background \
            --pidfile "$PIDFILE" \
            --make-pidfile \
            --exec "$DAEMON_PATH" -- $DAEMON_OPTS
        ;;
    stop)
        echo "Stopping $DAEMON_NAME"
        start-stop-daemon --stop --quiet \
            --pidfile "$PIDFILE" \
            --retry TERM/5/KILL/1
        rm -f "$PIDFILE"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0